#!/usr/bin/env python3
"""Generate a Mermaid graph of the app's Riverpod provider dependencies.

Reads the declared ``@Riverpod(dependencies: [...])`` annotations under lib/ and
writes a Mermaid ``flowchart``. Standard library only — no third-party deps.

Usage:
    python3 scripts/provider_graph.py                      # -> docs/provider_graph.md
    python3 scripts/provider_graph.py docs/graph.md        # custom markdown path
    python3 scripts/provider_graph.py graph.mmd            # raw mermaid (no md fence)

A ``.md`` output wraps the graph in a ```mermaid block (GitHub renders it); a
``.mmd`` output is the raw graph for https://mermaid.live or the mermaid CLI.
"""
import os
import re
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
LIB_DIR = os.path.join(PROJECT_ROOT, "lib")
DEFAULT_OUT = os.path.join(PROJECT_ROOT, "docs", "provider_graph.md")
HUB = "HikariPod"  # most depended-on; highlighted separately

_ANNOTATION = re.compile(r"@[Rr]iverpod\b(?:\s*\((?P<args>.*?)\))?", re.S)
_CLASS = re.compile(r"class\s+(\w+)\s+extends\s+_\$\1")
_FUNC = re.compile(r"(\w+)\s*\(\s*(?:\w+\s+)?[Rr]ef\b")
_DEPS = re.compile(r"dependencies\s*:\s*\[(.*?)\]", re.S)


def collect_edges(lib_dir):
    """Map each provider to the set of providers it declares a dependency on."""
    edges = {}
    for dirpath, _, files in os.walk(lib_dir):
        for name in files:
            if not name.endswith(".dart") or name.endswith((".g.dart", ".freezed.dart")):
                continue
            src = open(os.path.join(dirpath, name), encoding="utf-8").read()
            for m in _ANNOTATION.finditer(src):
                tail = src[m.end():m.end() + 400]
                cls = _CLASS.search(tail)
                fn = _FUNC.search(tail)
                provider = cls.group(1) if cls else (fn.group(1) if fn else None)
                if provider is None:
                    continue
                deps = set()
                dm = _DEPS.search(m.group("args") or "")
                if dm:
                    deps = {d.strip() for d in dm.group(1).split(",") if d.strip()}
                edges.setdefault(provider, set()).update(deps)
    # Ensure every referenced dep is also a node.
    for dep in {d for ds in edges.values() for d in ds}:
        edges.setdefault(dep, set())
    return edges


def build_mermaid(edges):
    nodes = sorted(edges)
    roots = [n for n in nodes if not edges[n]]

    lines = [
        "flowchart LR",
        "  classDef root fill:#fbedd8,stroke:#a85d0c,color:#a85d0c;",
        "  classDef hub fill:#dcf1f1,stroke:#0e7c86,color:#0e7c86,font-weight:bold;",
    ]
    for n in nodes:
        for d in sorted(edges[n]):
            lines.append(f"  {n} --> {d}")  # dependent --> dependency
    for r in roots:
        lines.append(f"  class {r} root;")
    if HUB in edges:
        lines.append(f"  class {HUB} hub;")
    return "\n".join(lines), nodes, roots


def render(mermaid, as_markdown):
    if not as_markdown:
        return mermaid + "\n"
    return (
        "# Provider dependency graph\n\n"
        "Generated by `scripts/provider_graph.py` from the declared "
        "`@Riverpod(dependencies: [...])`. Do not edit by hand — re-run the script.\n\n"
        "Arrows point from a provider to what it depends on. "
        "Amber = root (no deps); teal = the `HikariPod` hub.\n\n"
        "```mermaid\n" + mermaid + "\n```\n"
    )


def main():
    out_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_OUT
    if not os.path.isdir(LIB_DIR):
        sys.exit(f"error: no lib/ directory at {LIB_DIR}")

    edges = collect_edges(LIB_DIR)
    mermaid, nodes, roots = build_mermaid(edges)
    content = render(mermaid, as_markdown=not out_path.endswith(".mmd"))

    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(content)

    in_degree = sum(1 for ds in edges.values() if HUB in ds)
    print(
        f"wrote {out_path}  ·  providers: {len(nodes)}  ·  roots: {', '.join(roots)}"
        f"  ·  most depended-on: {HUB} ({in_degree})"
    )


if __name__ == "__main__":
    main()
