name: REUSE

on:
  push:
    branches: ["main", "publish"]
    tags-ignore: ["**"]
  pull_request:
    branches: ["main", "publish"]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: REUSE lint
        uses: fsfe/reuse-action@v6
